### ISSUE TITLE
3002漏了对结果进行判断吗？

### ISSUE THREAD

**Issue by 03128crz** [casatwy/CTPersistance#11]
/\* 3002 */
    NSDictionary *keyvalueList = @{@"migration1_0":@"this is migration"};
    NSString *whereCondition = @":primaryKey > 0";
    NSString *primaryKey = [table primaryKeyName];
    NSDictionary *whereConditionParams = NSDictionaryOfVariableBindings(primaryKey);
    [table updateKeyValueList:keyvalueList whereCondition:whereCondition whereConditionParams:whereConditionParams error:&error];

```
/* test 3003 */
```

**Comment by casatwy** [comment]
嗯，应该是漏掉了，3002和3003这里的测试用例没有写全，写了一半后来给我忘掉了～
