### ISSUE TITLE
TestCase跑完之后，根据MigrationStep2_0.m，数据表test并没有增加migration2_0 这个column

### ISSUE THREAD

**Issue by 03128crz** [casatwy/CTPersistance#12]
![snip20151028_2](https://cloud.githubusercontent.com/assets/3424553/10764311/7c7aee58-7d08-11e5-9b9a-a3340bc40683.png)

![snip20151028_1](https://cloud.githubusercontent.com/assets/3424553/10764272/4dff58de-7d08-11e5-8a46-8ed977cc5921.png)

**Comment by casatwy** [comment]
你下断点的话，能跑到这行代码吗？

如果没有跑到的话，可能你migration配置有问题，可以参考readme里面关于migration的Quick Try

**Comment by 03128crz** [comment]
直接运行项目的TestCase哦

**Comment by casatwy** [comment]
我当时测试的migration代码其实已经删掉了，你的测试方案是什么？

**Comment by 03128crz** [comment]
看readme里的说明，只要类符合说明，并且有建立了相应的plist文件，只要任意一个TestCase运行了，migration就由框架自动运行，难道我理解错了？

**Comment by casatwy** [comment]
你这部分理解得没错。还有另一部分，migration会根据versiontable中的数据来决定是否要进行migrate，而不是去比对每个表的差异而决定是否进行migrate。

所以如果正常跑testcase，是不会跑到migration的，你要想测试migration，就要先修改versiontable中的版本

**Comment by 03128crz** [comment]
总算弄清楚了，目前在理解代码中，希望以后有机会提PR，做点贡献 :)
