### ISSUE TITLE
创建表时如何添加外键约束？

### ISSUE THREAD

**Issue by jessedog** [casatwy/CTPersistance#15]
创建表被设计成只能指定字段及类型后，请问应该如何去添加外键约束呢?

**Comment by casatwy** [comment]
现在的CTPersistance不支持外键，因为我持外键其实是个伪需求的观点。

发自我的 iPhone

**Comment by jessedog** [comment]
哦~，那就只能自己去处理依赖关系，保持数据的完整性了。谢谢解答😁
