### ISSUE TITLE
当主键是字符串时，根据主键查询会报错

### ISSUE THREAD

**Issue by jessedog** [casatwy/CTPersistance#16]
错误信息的一部分“WHERE primaryKey = 987D5D73-4E98-49D5-A095-19610A3E8EEB 
 Error Message is: unrecognized token: "987D5D73"”

应该是“- (NSString *)stringWithSQLParams:(NSDictionary *)params”这个方法在拼接参数的使用没有把主键值用“''”单引号包起来的原因。
改成""...  WHERE primaryKey = '987D5D73-4E98-49D5-A095-19610A3E8EEB' ”就好了

**Comment by casatwy** [comment]
嗯，这其实是一个很复杂的问题，如果给所有主键都包一个引号，当主键为数字时又会出错，我需要解析一下主键类型再拼sql才行

发自我的 iPhone

**Comment by jessedog** [comment]
嗯，应该不只是主键，用其他键来查询应该也有这个问题。也许可以通过params里面的value类型来判断是否需要加引号

**Comment by Vincentzzg** [comment]
这个问题还没解决吗？查找的时候也是一样，如果value在表中是TEXT类型，就查不出来，少了单引号''
- (NSArray <NSObject <CTPersistanceRecordProtocol> _> *)findAllWithKeyName:(NSString *)keyname value:(id)value error:(NSError *_)error;

**Comment by casatwy** [comment]
主键目前强制要求是NSNumber，但是使用(NSArray > *)findAllWithKeyName:(NSString *)keyname value:(id)value error:(NSError *)error;这个函数去查找value为string的值已经OK了，昨天发布的1.3.0解决的就是这个问题。

**Comment by Vincentzzg** [comment]
刚刚测试了1.3.0问题还在：
Query Error: 
 Origin Query is : SELECT \* FROM 'pluginInfo' WHERE packagename = com.hikvision.moa.unlockuser 
 Error Message is: near ".": syntax error

1、这一串是我的value，报错了。
2、即便value是一串常规字符串，比如@”abc“，我刚刚插入的，用工具能查到，但是就是查不出数据，改成@"'abc'"之后就能查到了
3、还有就是不是应该所有的where条件里面条件值如果是text类型都应该要带单引号''的吗，我数据库不熟，但是其他的update、delete同样存在text类型的数据操作失效的问题

楼主可以测试下看

**Comment by Vincentzzg** [comment]
刚才又看了一下，这个要改的话应该是在NSString+SQL.h文件的
- (NSString *)stringWithSQLParams:(NSDictionary *)params;
  这个函数里面，在拼接字符串的时候，先判断value的类型，如果是NSString，加''
  NSString *value = @"";
  if ([params[key] isKindOfClass:[NSString class]]) {
  value = [NSString stringWithFormat:@"'%@'", params[key]];
  } else {
  value = [NSString stringWithFormat:@"%@", params[key]];
  }

不知道考虑的是否全面，你看下这样可以不

**Comment by casatwy** [comment]
我正在改这部分，改起来其实比你说的要复杂。我已经改好了，正在发1.3.1

**Comment by casatwy** [comment]
1.3.1已经发好了，相关测试用例是1008和1009

**Comment by Vincentzzg** [comment]
OK
