### ISSUE TITLE
CTPersistanceAsyncExecutor在Release下运行会死循环

### ISSUE THREAD

**Issue by xchen12** [casatwy/CTPersistance#18]
```
while (shouldWait) {
}
```

这个循环语句在release下编译，编译器会认为shouldWait不会被修改而不会每次去取值，导致死循环。在shouldWait变量前声明volatile可解决。另外，为啥不直接用- (void)addOperations:(NSArray<NSOperation *> *)ops waitUntilFinished:(BOOL)wait？

**Comment by casatwy** [comment]
嗯，这确实是一个bug

采用- (void)addOperations:(NSArray *)ops waitUntilFinished:(BOOL)wait也一样可以达到目的。我当初写的时候第一想到的其实还是while这种写法，只是个人选择不同
