### ISSUE TITLE
如果有多个数据库，都有数据迁移的需求，如何配置CTPersistanceConfiguration.plist文件？

### ISSUE THREAD

**Issue by MappleHero** [casatwy/CTPersistance#23]
场景：我有多个业务模块，分别做成不同的私有Pod。其中每个业务模块都使用CTPersistance创建自己模块数据库，每个数据库也都有对应的Migrator。但是有个问题，CTPersistance提供的配置文件CTPersistanceConfiguration.plist只有一份，如果在私有库中的CTPersistanceConfiguration.plist文件配置，当合并到主工程时，如果主工程或者别的私有库也有CTPersistanceConfiguration.plist文件，那么就会出现文件重复。这样的场景下，即如果有分库的需求时，如何进行数据迁移的配置呢？

谢谢~~

**Comment by casatwy** [comment]
这个问题不要在这里问，在文章下面问。

**Comment by casatwy** [comment]
私有pod中的CTPersistanceConfiguration.plist文件不要带入主工程就好了，然后主工程留的那个plist记录所有的migration信息
