### ISSUE TITLE
如何自定义sql语句，实现没有数据就插入，有数据就更新功能

### ISSUE THREAD

**Issue by MappleHero** [casatwy/CTPersistance#26]
我的需求场景是：如果表中没有数据，就是插入最新数据；如果表中有数据，就用最新数据替换表中数据。而目前CTPersistance中已经提供的分类没有这样给我提供sql语句的方法。

**Comment by casatwy** [comment]
CTPersistance已经提供直接执行SQL的方法了，在CTPersistanceTable中就有execute和fetchwithsql方法。

发自我的 iPhone
