### ISSUE TITLE
多线程test 6002中table是在Async block外创建，但运行成功？

### ISSUE THREAD

**Issue by lumouren009** [casatwy/CTPersistance#27]
我在文档里看到
方法:
- (void)performAsyncAction:(void (^)(void))action shouldWaitUntilDone:(BOOL)shouldWaitUntilDone;
  的注释里写到：
  you must always create CTPersistanceTable in action block, do not use outside table instance in this block
  但是在test 6002里面发现mainTestTable是在block外创建的，运行测试仍然成功。想问下这里是否与冲突？

**Comment by casatwy** [comment]
crash几率很小，但还是会导致crash的。我写test 6002的目的只是为了给另一个测试做准备。
