### ISSUE TITLE
terminating with uncaught exception of type nil

### ISSUE THREAD

**Issue by 03128crz** [casatwy/CTPersistance#3]
环境是xcode7 ，模拟器运行6s plus
![snip20151015_19](https://cloud.githubusercontent.com/assets/3424553/10517693/7b7bb3b0-7390-11e5-81fd-cc67fedd5263.png)

**Comment by casatwy** [comment]
嗯，这目前是whereCondition的一个bug，我正在调整whereCondition的实现。其实是 #1 导致的

**Comment by casatwy** [comment]
已修复
