### ISSUE TITLE
代码中用NSLog打印日志的代码太多了

### ISSUE THREAD

**Issue by MarsCWD** [casatwy/CTPersistance#32]
代码中有太多调用系统的NSLog来打印日志了，能否用个宏控制下，Debug模式下用NSLog打印，Release模式下不打印，稍微优化下

**Comment by casatwy** [comment]
我应该已经优化好了啊，你pod update一下呢？

发自我的 iPhone

在 2016年6月25日，21:04，chenweidong <notifications@github.com<mailto:notifications@github.com>> 写道：

代码中有太多调用系统的NSLog来打印日志了，能否用个宏控制下，Debug模式下用NSLog打印，Release模式下不打印，稍微优化下

―
