### ISSUE TITLE
Escape character of single quote doesn't work

### ISSUE THREAD

**Issue by DamianSheldon** [casatwy/CTPersistance#33]
# 

Query Error: 
 Origin Query is : INSERT INTO `BBCMessageDetailTable` (`id`,`isReaded`,`sendTime`,`fromId`,`toId`,`owner`,`msgType`,`orderId`,`orderType`,`peer`,`status`,`content`) VALUES (NULL,'0','1467975653','16122','22','16122','0','157','2','22','2','I\'m ');
#  Error Message is: near "m": syntax error

sqlite> INSERT INTO `BBCMessageDetailTable` (`id`,`isReaded`,`sendTime`,`fromId`,`toId`,`owner`,`msgType`,`orderId`,`orderType`,`peer`,`status`,`content`) VALUES (NULL,'0','1467975653','16122','22','16122','0','157','2','22','2','I\'m ');
   ...> );
   ...> ');
Error: near "m": syntax error

sqlite> INSERT INTO `BBCMessageDetailTable` (`id`,`isReaded`,`sendTime`,`fromId`,`toId`,`owner`,`msgType`,`orderId`,`orderType`,`peer`,`status`,`content`) VALUES (NULL,'0','1467975653','16122','22','16122','0','157','2','22','2','I''m ');
sqlite> select \* from BBCMessageDetailTable;
0|0|1467972148|22|Q really |16122|0|156|2|22|1|16122
1|0|1467972118|22|The best |16122|0|156|2|22|2|16122
2|0|1467975594|22|Even |16122|0|157|2|22|1|16122
3|0|1467975622|22|Do not |16122|0|157|2|22|1|16122
4|0|1467975653|22|Im |16122|0|157|2|22|2|16122
5|0|1467975653|22|I'm |16122|0|157|2|22|2|16122

**Comment by casatwy** [comment]
thank you for your report, and I have fixed this bug in tag 1.2.7
