### ISSUE TITLE
test case 3004 报 terminating with uncaught exception of type nil

### ISSUE THREAD

**Issue by jackhmy** [casatwy/CTPersistance#38]
![image](https://cloud.githubusercontent.com/assets/13128057/20297714/daba4d1a-ab4c-11e6-879a-2c1919d10dde.png)
![image](https://cloud.githubusercontent.com/assets/13128057/20297745/f4425d0e-ab4c-11e6-88b6-172399e38eb9.png)

record的name参数没有更新成功。
UPDATE `test` SET `name`='cary' WHERE primaryKey IN ('1,2,3')   经过测试，这条语句没有执行成功

**Comment by casatwy** [comment]
已经发布1.3.2，修复了这个问题
