### ISSUE TITLE
1.3.2数据查询失效

### ISSUE THREAD

**Issue by Vincentzzg** [casatwy/CTPersistance#39]
今天更新插件的时候升级到了1.3.2，发现数据库操作全都失效了。看了下楼主的提交更新才明白了又是之前那个''的问题。
针对这种    NSString *sqlString = @"SELECT * FROM ':tableName' WHERE conversationId = ':conversationId' ORDER BY messageTime DESC limit ':index',':count'";
语法，前面带:冒号的参数都增加了''，查询OK了
但是
    NSArray *recordList = [self.contactInfoTable findAllWithKeyName:@"shortName" value:shortName error:&error];
这种查询又失效了，点进去看了一下，分类里面参数楼主没有加''
![2016-11-25 4 38 22](https://cloud.githubusercontent.com/assets/10241716/20619098/9ffda472-b32d-11e6-8386-6933d649bc9e.png)

这里似乎又回到了1.3.0的缺少''语法问题

之前的问题 https://github.com/casatwy/CTPersistance/issues/37 就是这个问题
数据库我不熟，语法也不太懂，只是测试出来是这个问题，楼主看下

**Comment by Vincentzzg** [comment]
我又问了下后台的同事，说是字符串类型的参数必须加''

**Comment by casatwy** [comment]
这个需要你业务这边手动加了，因为我很难判断一个value到底是字符串还是数字～

在 2016年11月25日，下午4:58，zhouzhongguang <notifications@github.com<mailto:notifications@github.com>> 写道：


我又问了下后台的同事，说是字符串类型的参数必须加''
