### ISSUE TITLE
你好大神

### ISSUE THREAD

**Issue by maqihan** [casatwy/CTPersistance#40]
我一直搞不懂一个问题，如果服务器将错误的数据类型返回给客户端（能使app崩溃），此时客户端将此数据保存了下来，那么对于app来说岂不是很危险。这种情况该怎么避免呢

**Comment by casatwy** [comment]
这个问题你应该去RTNetworking下面问吧？

RTNetworking的baseapimanager里面有validator，在缓存逻辑中，只有经过validator验证通过的返回数据才会被缓存。
