### ISSUE TITLE
iOS离线缓存，在线同步到服务器可以用这个吗？

### ISSUE THREAD

**Issue by xiaohange** [casatwy/CTPersistance#42]
为了提高用户体验，我们在将用户操作与api分开了，准备开发一个带有自动检测是否有要update，load，insert等通过api进行下载，上传，更新本地数据库功能，请问推荐使用这个吗？

**Comment by casatwy** [comment]
不建议在持久层做，因为这是弱业务。

你应该单独开一个DataManager，用这个DataManager操作APIManager和DataCenter，以及协调他们的交互。

DataManager去检测DataCenter是否需要更新，如果需要，它再调度APIManager去获得数据，拿到数据之后，再把数据交给DataCenter去更新。

**Comment by xiaohange** [comment]
@casatwy  谢谢你的建议！
