### ISSUE TITLE
字符串做主键插入的问题

### ISSUE THREAD

**Issue by ghost** [casatwy/CTPersistance#43]
在插入新数据之后会强制把 `lastInsertRowId`设置为主键的值，但是这个值类型和数据是错误的， 请问该如何处理这种情况？

**Comment by heistings** [comment]
我看了代码，框架采用了自增主键的设计，这意味着主键类型被锁死在 INTEGER 这个类型上了。 一个可能的原因是使用 INTEGER 作为主键能够提升查询效率。

你需要做的是手动维护业务逻辑上的 “主键” ，保证其唯一性。

**Comment by casatwy** [comment]
@heistings 说得没错
