### ISSUE TITLE
关于主键是字符串的问题

### ISSUE THREAD

**Issue by jackhmy** [casatwy/CTPersistance#46]
当主键是字符串的时候，在获取操作中有findAllWithKeyName可以进行查找。但是当需要通过主键删除一条记录的时候就没有相应的方法了，可不可以在删除deleteRecord的系列方法中也添加类似deleteRecordWithKeyName呢，会不会有其他隐患？

**Comment by casatwy** [comment]
`- (void)deleteWithWhereCondition:(NSString *)whereCondition conditionParams:(NSDictionary *)conditionParams error:(NSError **)error;`

这个解决不了你的需求么？

**Comment by jackhmy** [comment]
这个和deleteWithSQL都可以解决
