### ISSUE TITLE
数据存储bug

### ISSUE THREAD

**Issue by jackhmy** [casatwy/CTPersistance#47]
当存储的字段为字符串类型，且字符串中有 ; 符号的时候， 会被safeSQLEncode 过滤掉，导致数据存储错误

**Comment by casatwy** [comment]
不好意思最近比较忙，这确实是一个问题，周末我会花时间彻底改造一下整个流程。

发自我的 iPhone

在 2017年7月3日，上午10:20，jackhmy <notifications@github.com<mailto:notifications@github.com>> 写道：


当存储的字段为字符串类型，且字符串中有 ; 符号的时候， 会被safeSQLEncode 过滤掉，导致数据存储错误

**Comment by casatwy** [comment]
在解决这个问题的过程中，我发现了CTPersistance更多的缺陷，我打算重写CTPersistance中SQL语句处理的相关部分。

所以一时半会儿这个问题会被搁置，在重写好之后，这个问题以及其相关的附属问题就会被解决了。

非常非常抱歉，希望没有影响到你的正常业务～

**Comment by jackhmy** [comment]
目前没有什么影响。
感谢casa大大的分享，大大的iOS架构谈以及后续文章对我影响深远。
期待重写之后的CTPersistance对更多的人适用

**Comment by casatwy** [comment]
哈，感谢你的支持和鼓励，我会尽快搞定CTPersistance的问题的😊
