### ISSUE TITLE
数据异步操作崩溃

### ISSUE THREAD

**Issue by Vincentzzg** [casatwy/CTPersistance#48]
大神帮忙看下。
一个socket请求，返回数据保存到本地数据库，偶尔会崩溃，不知道什么问题

代码我贴一下：
1、请求数据
![2017-07-11 2 54 10](https://user-images.githubusercontent.com/10241716/28054801-fc2f2670-6648-11e7-8c5f-a8f1be56f5b8.png)

![2017-07-11 2 47 55](https://user-images.githubusercontent.com/10241716/28054631-4895950e-6648-11e7-842b-9634e656d623.png)

2、保存数据
![2017-07-11 2 48 16](https://user-images.githubusercontent.com/10241716/28054639-4d656aaa-6648-11e7-8926-962103eed23f.png)

3、崩溃点
![2017-07-11 2 48 24](https://user-images.githubusercontent.com/10241716/28054641-50ed9986-6648-11e7-8287-dfb9a8eeaf56.png)

报错信息：
![2017-07-11 2 51 37](https://user-images.githubusercontent.com/10241716/28054674-75747db0-6648-11e7-9c3f-a81a45983a2f.png)

**Comment by sun6boys** [comment]
那你图3crash的时候函数调用栈能发个截图吗，另外存储公众号列表之前有一个清除操作，把清除操作的那段代码也截图发一下吧。

**Comment by Vincentzzg** [comment]
@sun6boys 调用栈第一张图左侧就是。

清空操作截图：
![2017-07-11 5 20 45](https://user-images.githubusercontent.com/10241716/28061492-58a5e4d4-665d-11e7-95f1-eb73dff21894.png)

**Comment by casatwy** [comment]
这个异步的过程我有修改过，新版本还会出现这样的问题么？

另外，不建议直接使用SQL操作
