### ISSUE TITLE
如何添加双主键

### ISSUE THREAD

**Issue by jackhmy** [casatwy/CTPersistance#49]
如题

**Comment by heistings** [comment]
我看了代码，框架采用了自增主键的设计，这意味着主键类型被锁死在 INTEGER 这个类型上了。 一个可能的原因是使用 INTEGER 作为主键能够提升查询效率。

我理解你说的应该是“联合主键”的概念。你可以尝试通过业务逻辑来维护“联合主键”，保证其唯一性。

**Comment by casatwy** [comment]
@heistings 说得没错
