### ISSUE TITLE
switf 4版本下，BuiltInBasicType.swift 文件有类型报错

### ISSUE THREAD

**Issue by single-dh** [casatwy/CTPersistance#52]
version: swift4 edition
HandyJSON version 1.8.0
问题：在BuiltInBasicType.swift文件中的第30行
 protocol IntegerPropertyProtocol: Integer, _BuiltInBasicType
提示Integer has been renamed to BinaryInteger

**Comment by casatwy** [comment]
CTPersistance暂时没打算支持Swift...
