### ISSUE TITLE
updateRecordList 异常

### ISSUE THREAD

**Issue by ucoker** [casatwy/CTPersistance#53]
在`CTPersistanceTable+Update.m`的方法   
`- (void)updateRecordList:(NSArray <NSObject <CTPersistanceRecordProtocol> *> *)recordList error:(NSError **)error`,  

若直接传入error值是nil或NULL,运行到这个方法会崩溃`Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)`，错误定位在29行` if (*error != nil) {` ，若传入的error 为 &error 则正常。

**Comment by casatwy** [comment]
改好了，版本号162
