### ISSUE TITLE
pod "CTPersistence" in the readme.md does not work

### ISSUE THREAD

**Issue by heistings** [casatwy/CTPersistance#54]
pod "CTPersistance"

**Comment by casatwy** [comment]
show me the error string?

**Comment by heistings** [comment]
Use `pod 'CTPersistance'` instead of `pod 'CTPersistence'`

**Comment by casatwy** [comment]
you should follow what the error string says.

**Comment by heistings** [comment]
You've made a mistake in the readme.md. The first line should be:

```
pod 'CTPersistance'
```

but it is now:

```
pod 'CTPersistence'
```

**Comment by casatwy** [comment]
yes, you are right. I have fixed this, thank you!
