### ISSUE TITLE
update 操作可能出现问题

### ISSUE THREAD

**Issue by BigNerdCoding** [casatwy/CTPersistance#55]
在进行数据库记录更新时，如果存在 **BLOB** 字段，那么可能出现问题。默认情形下，数据更新操作并不会调用 *bindBlobWithStatement* 函数，也就是说 *sqlite3_bind_blob* 不会被执行，这样会导致一个 BLOB 类型字段不会被更新，甚至被更新为 **NULL**。除非再额外调用一次 BLOB 类型字段 对应的更新操作。

```
// 该操作不会更新  BLOB 类型字段
[table updateRecord:record error:&error];

// 需要以下操作才能实现真正的更新
[table updateRecord:record error:&error];
[table updateValue:record.bleData forKey:@"bleData" primaryKeyValue:record.identifier error:&error];
```

不知道作者能否在后面对 *updateRecord* 进行补充？

**Comment by casatwy** [comment]
好的，我吃完饭改一下

**Comment by casatwy** [comment]
改好了，版本号161

**Comment by BigNerdCoding** [comment]
@casatwy 谢谢你
