### ISSUE TITLE
空值对象的改进问题

### ISSUE THREAD

**Issue by BigNerdCoding** [casatwy/CTPersistance#59]
对于数据库 **NULL** 值当前设计是在 *fetchWithError* 函数中将其设置为 *[NSNull null]* 单例对象。在 OC 环境下这种设计绝大多数情形下不会存在太大的问题，但是对于 Swift 混编环境来说该设计明显对 Optional 值不友好，使用不当存在潜在 Crash 问题。另一个是对于值对象来说：即使是 OC 环境，*[NSNull null]* 单例对象在动态转化为 long long 等值时存在 Runtime Crash （当然这个在插入记录的时候就存在使用不当，值类型不应使用空值，但是 CT  Runtime 提供了这部分操作的能力 ）。

如果我们将改部分处理代码改为：

```
case SQLITE_NULL:
        [result setObject:nil forKey:columnName];
        break;
```

可能对使用者来说更好一点。

另一个，空值改进的方法我觉得后期可以考虑一下：对 *CTPersistanceTableProtocol* 进行一个拓展，增加一个 *columnDefaultValue* 方法用于设置默认值。这样使用者可以通过该协议设置默认值从而避免空值对象问题，而不是在插值之前人为保证。

**Comment by casatwy** [comment]
新版已改好，165

存入的数据是nil的话，取出来的时候数据就也是nil
