### ISSUE TITLE
CTPersistanceDatabasePool 中的一些问题

### ISSUE THREAD

**Issue by BigNerdCoding** [casatwy/CTPersistance#61]
数据库链接池存在一些问题，我提一下：

1. databaseWithName 方法构造链接时使用的 Key 与 closeDatabaseWithName 不一致，所以存在 closeDatabaseWithName 失败甚至 Crash 问题 （database 为 nil 无法响应 closeDatabase ）
2. 如果使用当前线程与 databaseName 为 Key ，那么多线程环境下同一数据库存在多个链接的可能，而 CT 本身并没有使用 WAL 模式所以可能存在同时写以及读写竞争问题
3. 建议数据库链接池采用 databasePath 作为 Key (可能存在同名数据库，所以不能使用 databaseName)，这样能保证同一个数据库只有一个链接
4. 不要内部自动关闭数据库链接，而且当前关闭也存在问题（同一线程下创建的多个链接可能只会关闭第一个，而且未从 databaseList 中移除）。关闭链接操作交由上层处理。
5. 如果用户手动删除数据库文件，但是没有关闭链接，则该情形属于使用不当，不作容错处理。

**Comment by casatwy** [comment]
已修复，我就先关闭了～

**Comment by Deeer** [comment]
@casatwy 请问是出于什么原因，不启用WAL模式？
我在项目中测试了一下，数据读写耗时降低了百分之十五左右/
