### ISSUE TITLE
CTPersistanceDataBase没有提供自己定义数据库路径的接口

### ISSUE THREAD

**Issue by hulala1210** [casatwy/CTPersistance#68]
Hi，大神！我又来麻烦您了。现在我有一份数据库文件，它是在Bundle中的，是我用来记录了一些常量，其中表都是类似这样子的
<img width="752" alt="image" src="https://user-images.githubusercontent.com/6939475/40602320-b80d0216-628a-11e8-90ca-e6414b8c3d65.png">
其中StringForAppDisplay是给App显示用的，CodeForServer是和后台服务器交互用的。主要是为了解决同样的数据，App显示数据和后台交互数据的不同的问题。

之前是自己用FMDB写SQL来查，现在想复用CTPersistance中的查询功能。但是看CTPersistanceDataBase的源码发现，CTPersistance能操作的数据库都只是在App的Library文件夹中，并不能访问到Bundle中的数据库文件。

我想请教一下：
1、如果我想复用CTPersistance的查询功能访问Bundle中的数据库文件，有什么比较优雅的做法没？
2、我用bundle中的数据库文件记录这种常量的设计是否合理（之前我是用Plist做，但是考虑到Plist容易被别人解包直接拿到数据，而且每次加载需要把整个Plist加载进内存。于是我改成了数据库的方式。数据库有设置加密密码，提高了一些数据安全性。并且我有配合NSCache来解决多次重复查询需要大量时间的问题）？如果不合理能否帮忙给点建议？

谢谢。

**Comment by casatwy** [comment]
1. CTPersistance是支持使用Bundle的文件的。

在[CTPersistanceDataBase.m:45](https://github.com/casatwy/CTPersistance/blob/master/CTPersistance/CTPersistance/Database/CTPersistanceDataBase.m#L45)的地方有一个获取数据库文件的方法。

你需要根据你的数据库名构建一个target，对应的action就是"filePath"，在这个target-action中返回完整的数据库文件地址即可。[用法在这里](https://github.com/casatwy/CTPersistance#target-action-in-ctpersistance)

简单举个例子就是，如果你的数据库文件叫做"aaa.sqlite"，那么CTPersistance会在操作table的时候，自动调度名为`Target_aaa`对象的`-(NSString *)Action_filePath:`方法来获得数据库具体地址，调用的时候会把数据库文件名作为参数传递过去。这个过程等价于这样的调用：

```
id target = [[Target_aaa alloc] init];
NSString *filePath = [target Action_filePath:@{kCTPersistanceConfigurationParamsKeyDatabaseName:@"aaa.sqlite"}];
```
所以你要做的事情就是在项目的任意地方，新建一个对象名叫`Target_aaa`，然后给到一个`-(NSString *)filePath:(NSDictionary *)params`的实现，在这个实现里面直接返回具体地址的NSString即可。

然后其他的table啊，record啊之类的操作，就都跟别的一样。如果CTPersistance调用不到这个实现，那么它就默认去library找，如果找不到就认为这个文件不存在，就会自动生成这个数据库文件。

2. CTPersistance同样也是支持数据库加密的，还是在`Target_aaa`对象中，给到一个`- (NSArray *)Action_secretKey:(NSDictionary *)params`的实现即可，这个实现返回的就是数据库加密的密码。如果不实现这个方法，那么就默认不加密数据库。

关于cache的事情，sqlite自己会解决的，你只管调用就好了。

**Comment by casatwy** [comment]
我刚刚在readme中补充了一下关于target-action的事情

**Comment by casatwy** [comment]
关于target对象的事情，你也不用管target对象什么时候init，你只要保证工程里有这个对象就可以了，CTPersistance会通过CTMediator，进而以runtime的方式去处理target-action的事情。

所有你要做的事情就是创建个target对象，实现好action方法，然后就放着。

就可以了。
