### ISSUE TITLE
objectRepresentationWithDictionary方法名的理由

### ISSUE THREAD

**Issue by DamianSheldon** [casatwy/CTPersistance#7]
从CTPersistanceRecordProtocol文件的的声明config your record with dictionary和CTPersistanceRecord的实现来看这个方法都偏向于是一个动作，是不是名称改成- (void)setPersistanceValuesForKeysWithDictionary:(NSDictionary *)keyedValues会更合适？还是这里这么命名是有其他深层的原因？

**Comment by casatwy** [comment]
嗯，取名objectRepresentation..是早期希望这是个类方法，直接返回一个类实例的，但因为VirtualRecord本身并不是一个类，所以这个命名就这么迁移过来了，没愿意去改～

**Comment by DamianSheldon** [comment]
哦，原来如此，里面确实还有不少方法名有类似历史问题，维护开源库不容易，有时间我也要加入进来，辛苦了，谢谢！
