### ISSUE TITLE
关于bindValueList

### ISSUE THREAD

**Issue by longjianjiang** [casatwy/CTPersistance#72]
刚看casa的这个库，发现使用sql语句的时候，很多地方用了bindValueList， 现在不是太理解这个有什么作用，为什么不直接用sql语句呢？ 希望casa解释下😁。

**Comment by casatwy** [comment]
主要是为了防止SQL注入，以及正确地给SQL语句中的变量做value替换。

你可以参考这里： https://www.sqlite.org/c3ref/bind_blob.html
