### ISSUE TITLE
当Table中没有数据的时候，Upsert一个带有PrimaryKey的Record，失败

### ISSUE THREAD

**Issue by hulala1210** [casatwy/CTPersistance#74]
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/6939475/42123131-3be859ce-7c7f-11e8-8e00-15d2f78e4172.png">
您好！
    问题如图：图上代码是CTPersistance中CTPersistanceTable +Upsert的源码。我插入一个Record，并且Record的PrimaryKey是字符串@"1"。在插入的瞬间，Table是没有任何数据的。然后代码走到了途中断点位置——“[weakSelf updateKeyValueList:valueToUpdate primaryKeyValue:[record valueForKey:weakSelf.child.primaryKeyName]  error:error];”一个没有数据的Table执行了Update操作。

请教一下是我哪里没有弄好，还是什么其他问题呢？

谢谢先！

**Comment by casatwy** [comment]
这个问题在184版解决了
