### ISSUE TITLE
数据库模糊查询findAllWithWhereCondition:@"name LIKE :name"，没有数据

### ISSUE THREAD

**Issue by Vincentzzg** [casatwy/CTPersistance#76]
数据库模糊查询时，使用方法findAllWithWhereCondition:@"name LIKE :name"查询数据库已有的数据，但是返回的结果为空

测试方法中，testFindAllWithWhereConditionConditionParamsIsDistinctFalse中的代码改成：
```
 NSArray <TestRecord *> *recordList = (NSArray <TestRecord *> *)[self.testTable findAllWithWhereCondition:@"name LIKE :name"
                                                                                             conditionParams:@{@":name":@"cas"}
                                                                                                  isDistinct:NO
                                                                                                       error:&error];
```
查询结果为空

底层代码看不懂，所以不知道问题在哪，只能提个Issues了

直接使用完整的sql语句
 ```
NSError *error = nil;
NSString *sqlString = [NSString stringWithFormat:@"SELECT * FROM application WHERE name LIKE '%%%@%%'", searchText];
NSArray *fetchList = [self.applicationTable fetchWithSQL:sqlString error:&error];
```
结果是对的

**Comment by casatwy** [comment]
``` 
NSArray <TestRecord *> *recordList = (NSArray <TestRecord *> *)[self.testTable findAllWithWhereCondition:@"name LIKE :name"
                                                                                             conditionParams:@{@":name":@"%%%@%%"}
                                                                                                  isDistinct:NO
                                                                                                       error:&error];
```

你这样试一下呢？

**Comment by Vincentzzg** [comment]
试了，可以的

**Comment by Vincentzzg** [comment]
`NSArray <TestRecord *> *recordList = (NSArray <TestRecord *> *)[self.testTable findAllWithWhereCondition:@"name LIKE :name"
                                                                                             conditionParams:@{@":name":@"%%name%%"}
                                                                                                  isDistinct:NO
                                                                                                       error:&error];
`
这样是可以的

但是换种写法就不行了，感觉这样才是更好的写法：
`NSArray <TestRecord *> *recordList = (NSArray <TestRecord *> *)[self.testTable findAllWithWhereCondition:@"name LIKE %%:name%%"
                                                                                             conditionParams:@{@":name":@"name"}
                                                                                                  isDistinct:NO
                                                                                                       error:&error];`

**Comment by casatwy** [comment]
后者的写法现在是不支持么？

**Comment by Vincentzzg** [comment]
是的，这种写法
`NSArray <TestRecord *> *recordList = (NSArray <TestRecord *> *)[self.testTable findAllWithWhereCondition:@"name LIKE %%:name%%" conditionParams:@{@":name":@"name"} isDistinct:NO error:&error];`

报语法错：
<NSThread: 0x282b46e00>{number = 1, name = main}

/Users/zhouzhongguang/GitHub/CTPersistance/CTPersistance/CTPersistance/QueryCommand/Statement/CTPersistanceSqlStatement.m
-[CTPersistanceSqlStatement initWithSqlString:bindValueList:database:error:](38):

	error is:
		 near "%": syntax error 

	 sqlString is SELECT * FROM `test` WHERE name LIKE %%:CTPersistanceWhere_name%%

======================

**Comment by casatwy** [comment]
后面那种写法实现不了，因为SQL是先编译成statement再绑定数值的。如果按照后面这种写法，编译SQL就报错了～
