### ISSUE TITLE
已有未加密数据库，增加加密功能出错

### ISSUE THREAD

**Issue by Vincentzzg** [casatwy/CTPersistance#78]
我又来了😄
数据库之前没有加密，现在要求加密，然后我就把秘钥的返回改了一下：
`- (NSArray <NSString * > * __nullable)Action_secretKey:(NSDictionary *)params {
//    return nil;
    return @[@"dghsaehrserhz"];
}`
然后重新启动APP调试，出问题了，报错如下：

======================

<NSThread: 0x281025280>{number = 6, name = (null)}

/Users/zhouzhongguang/客户端/iOS-HikMoa/Pods/CTPersistance/CTPersistance/CTPersistance/QueryCommand/Statement/CTPersistanceSqlStatement.m
-[CTPersistanceSqlStatement initWithSqlString:bindValueList:database:error:](38):

	error is:
		 file is not a database 

	 sqlString is SELECT name FROM sqlite_master WHERE type='table';

======================

是需要升级一个数据库版本吗？那么MigrationStep6_0里面是不是什么都不用写？

**Comment by casatwy** [comment]
加密的话，要重建数据库的，因为之前的数据库文件不是加密之后的文件，是明文文件。

你现在给了密钥，那么框架就会用加密文件的格式去读，结果读到了一个明文格式的文件，那就出错了。

**Comment by Vincentzzg** [comment]
那是要升级数据库版本吗？

**Comment by casatwy** [comment]
不需要啊，这是数据库文件格式的问题，跟数据库版本没关系的。

你要做的是起一个新的数据库，加密的。然后把旧的明文数据库里的数据导入到新的加密的数据库中。

**Comment by Vincentzzg** [comment]
数据库操作我不熟，我说下我的理解，是不是说需要更新每个table里面databaseName字段，然后在APP启动时进行业务数据读写之前，遍历老的数据库文件中每个表的数据然后挨个插入到新的数据库？还是有整体移动数据的方法

**Comment by casatwy** [comment]
我说的不是这个。

你可以理解成整个数据库是一个文件，这个文件里面有各种表。

这个文件有加密版的和明文版的两种格式。

你如果带着密钥去操作一个数据库，那么sqlite就会以加密版的格式去解析这个数据库文件。

你如果不带着密钥去操作一个数据库，那么sqlite就会以加密版的格式去解析这个数据库文件。

现在你的情况是，之前你用数据库的时候是不带密钥的，所以数据库是明文版的，所以sqlite在刚开始的时候是以明文的格式创建了数据库文件。

然后你现在操作数据库的时候带了密钥，那么sqlite就会用加密版的方法去解析你指定的数据库文件。但很不幸，这个数据库文件之前是明文版的格式创建的，所以sqlite就无法解析这个数据库文件了，所以它就认为要解析的这个数据库文件不是一个数据库，就报错了。

你要做的事情就是，把原来明文的数据全部读出来，然后带着密钥让sqlite以加密的方式写到新的加密版的数据库里面去，数据迁移完了之后，再把那个明文版的数据库文件删掉。



发自我的 iPhone

在 2019年3月5日，下午3:44，zzg <notifications@github.com<mailto:notifications@github.com>> 写道：


数据库操作我不熟，我说下我的理解，是不是说需要更新每个table里面databaseName字段，然后在APP启动时进行业务数据读写之前，遍历老的数据库文件中每个表的数据然后挨个插入到新的数据库？还是有整体移动数据的方法

**Comment by casatwy** [comment]
这个可能有工具直接可以做到迁移的事情，但我不知道，你可以找找看。

发自我的 iPhone

在 2019年3月5日，下午3:44，zzg <notifications@github.com<mailto:notifications@github.com>> 写道：


数据库操作我不熟，我说下我的理解，是不是说需要更新每个table里面databaseName字段，然后在APP启动时进行业务数据读写之前，遍历老的数据库文件中每个表的数据然后挨个插入到新的数据库？还是有整体移动数据的方法

**Comment by Vincentzzg** [comment]
谢谢解答
明白了，是要脱离当前这个CTPersistance库来解决这个问题，就是把本地数据库文件由未加密转成加密的数据库文件，只是加密的key值要跟Action_secretKey里面返回的一致。文件转成加密之后就可以继续正常使用CTPersistance库的所有功能

**Comment by casatwy** [comment]
对的

发自我的 iPhone

在 2019年3月6日，上午11:13，zzg <notifications@github.com<mailto:notifications@github.com>> 写道：


谢谢解答
明白了，是要脱离当前这个CTPersistance库来解决这个问题，就是把本地数据库文件由未加密转成加密的数据库文件，只是加密的key值要跟Action_secretKey里面返回的一致。文件转成加密之后就可以继续正常使用CTPersistance库的所有功能
