### ISSUE TITLE
"Include of non-modular header inside framework module"

### ISSUE THREAD

**Issue by kevinrenskers** [casatwy/CTPersistance#81]
I have taken over an existing project that uses CTVideoPlayerView, and thus in turn CTPersistance. Sadly I can't get the project to compile because of the following error:

<img width="866" alt="Screen Shot 2019-07-16 at 10 13 05" src="https://user-images.githubusercontent.com/229384/61277491-922dc080-a7b2-11e9-8a05-9055163f5b39.png">

I am using the latest Xcode, latest Cococapods. Project targets iOS 11.1 and higher. It's a Swift project.

The bridging header simply contains this line:

```
#import <CTVideoPlayerView/CTVideoView.h>
```

And this fails (error "Could not build module 'CTVideoPlayerView'") because of the problem with CTPersistance. I'm using the latest pods of both CTVideoPlayerView and CTPersistance.

Any idea what could be wrong?

**Comment by casatwy** [comment]
bug fixed
