### ISSUE TITLE
[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: jsonString) crash

### ISSUE THREAD

**Issue by 1257331501** [casatwy/CTPersistance#84]
-[CTPersistanceSqlStatement fetchWithError:] (CTPersistanceSqlStatement.m:0)
-[CTPersistanceTable(Find) findAllWithSQL:params:error:]  (CTPersistanceTable+Find.m:57)
调用堆栈如上
应该是崩溃在   [result setObject:@(value) forKey:columnName]  vaule为nil 时
麻烦修复下谢谢

**Comment by casatwy** [comment]
有没有可以复现的代码？

我看代码，这里没有可能value是nil

<img width="491" alt="截屏2020-08-24 20 12 40" src="https://user-images.githubusercontent.com/1005781/91043512-49e40180-e646-11ea-8c00-87ea2d487188.png">

**Comment by 1257331501** [comment]
crash 系统看到的 崩溃率太低了 尝试多次 无法复现 后续观察吧，谢谢回复

**Comment by casatwy** [comment]
嗯，这部分代码我看也不会崩，调用sqlite的函数取到的数字转成NSNumber，我怎么看都不会为nil
