### ISSUE TITLE
小白问下，表文件创建后能添加新字段吗

### ISSUE THREAD

**Issue by YJH94** [casatwy/CTPersistance#85]
比如之前只有name ，age 这些字段， 后面app升级了，加了 avatar， 这是要重新建表吗，还是能直接表中插入字段

**Comment by casatwy** [comment]
可以的，走migration就行了，test case里有migration的示例，只要发现有最新的migration，就会自动更新表结构

**Comment by casatwy** [comment]
https://github.com/casatwy/CTPersistance#target-action-in-ctpersistance
