### ISSUE TITLE
你个博客http://casatwy.com无法打开。求增加字段升级数据库操作文档。

### ISSUE THREAD

**Issue by 1257331501** [casatwy/CTPersistance#88]

**Comment by 1257331501** [comment]
只是无法打开博客而已

**Comment by casatwy** [comment]
现在应该可以打开了

**Comment by 1257331501** [comment]
Hi castaway:
&nbsp; &nbsp; &nbsp; 表中新增字段，需要升级数据库，因数据库有不同版本中各种表字段都可能不一样，每次升级都胆战心惊，不到万不得已，绝不升级。如果遇到必须升级数据库的时候，只能硬着头皮上，出了问题就会被打低绩效走人。看大佬写的测试用例，还是不太明白如何操作（是我太菜了），求大佬出一篇数据升级原理和操作的的博客，最好有伪代码展示或者在github中，描述清楚如何升级和原理。跪求










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "casatwy/CTPersistance"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月11日(星期四) 上午10:11
收件人:&nbsp;"casatwy/CTPersistance"<CTPersistance@noreply.github.com&gt;;
抄送:&nbsp;"韩阳"<1257331501@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [casatwy/CTPersistance] 你个博客http://casatwy.com无法打开。求增加字段升级数据库操作文档。 (#88)





 
现在应该可以打开了
